# Site settings
title: Forced to Flee
email: your-email@domain.com
description: Forced to flee. The refugee crisis is real. Nearly 60 million people have beeen forced to flee their homes worldwide. The numbers will rise. Get educated get involved and take action to help us stop the crisis.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://forcedtoflee.com" # the base hostname & protocol for your site

permalink: pretty

# Build settings
markdown: kramdown

exclude: [vendor,'Gemfile','Gemfile.lock','Readme.md']

#Assets Pipeline
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets
